// <auto-generated />
using System;
using Backend.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260802142309_RemoveImportInfoAtDueToDuplication")]
    partial class RemoveImportInfoAtDueToDuplication
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("AppliedTagCollection", b =>
                {
                    b.Property<long>("AppliedTagsId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CollectionsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppliedTagsId", "CollectionsId");

                    b.HasIndex("CollectionsId");

                    b.ToTable("CollectionAppliedTags", (string)null);
                });

            modelBuilder.Entity("AppliedTagMediaFile", b =>
                {
                    b.Property<long>("AppliedTagsId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MediaFilesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppliedTagsId", "MediaFilesId");

                    b.HasIndex("MediaFilesId");

                    b.ToTable("MediaFileAppliedTags", (string)null);
                });

            modelBuilder.Entity("AppliedTagTagModifier", b =>
                {
                    b.Property<long>("AppliedTagId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ModifiersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppliedTagId", "ModifiersId");

                    b.HasIndex("ModifiersId");

                    b.ToTable("AppliedTagModifiers", (string)null);
                });

            modelBuilder.Entity("Backend.Models.AppliedTag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CombineWord")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long?>("CombinedWithId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CombinedWithId");

                    b.HasIndex("TagId");

                    b.ToTable("AppliedTags");
                });

            modelBuilder.Entity("Backend.Models.Collection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastViewed")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameLowerCase")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("PreviewMediaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NameLowerCase")
                        .IsUnique();

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("Backend.Models.CollectionItem", b =>
                {
                    b.Property<long>("CollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MediaFileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("CollectionId", "MediaFileId");

                    b.HasIndex("MediaFileId");

                    b.HasIndex("CollectionId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("CollectionItem");
                });

            modelBuilder.Entity("Backend.Models.DownloadGallery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentlyScannedUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("GalleryName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("GalleryUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDownloaded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagsString")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GalleryUrl")
                        .IsUnique();

                    b.ToTable("DownloadGalleries");
                });

            modelBuilder.Entity("Backend.Models.IgnoredDuplicate", b =>
                {
                    b.Property<long>("MediaFileId1")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MediaFileId2")
                        .HasColumnType("INTEGER");

                    b.HasKey("MediaFileId1", "MediaFileId2");

                    b.HasIndex("MediaFileId2");

                    b.ToTable("IgnoredDuplicates");
                });

            modelBuilder.Entity("Backend.Models.MaintenanceJobRecord", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Failed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastPerformed")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextRunAfter")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusMessage")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("MaintenanceJobRecords");
                });

            modelBuilder.Entity("Backend.Models.MediaFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CropBottom")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CropLeft")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CropRight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CropTop")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FrameCount")
                        .HasColumnType("INTEGER");

                    b.Property<float>("FramesPerSecond")
                        .HasColumnType("REAL");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorited")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTemporary")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastViewed")
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameLowerCase")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ParentMediaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stars")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("ParentMediaId");

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("Backend.Models.MediaFolder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameLowerCase")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MediaFolders");
                });

            modelBuilder.Entity("Backend.Models.MediaImportInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DownloadGalleryId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MediaFileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreferredName")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Referrer")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsString")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DownloadGalleryId");

                    b.HasIndex("MediaFileId")
                        .IsUnique();

                    b.ToTable("MediaImportInfos");
                });

            modelBuilder.Entity("Backend.Models.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExampleMediaId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExampleMediaId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Backend.Models.TagAlias", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TagId");

                    b.ToTable("TagAliases");
                });

            modelBuilder.Entity("Backend.Models.TagBreakRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ActualTagId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagString")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActualTagId");

                    b.HasIndex("TagString")
                        .IsUnique();

                    b.ToTable("TagBreakRules");
                });

            modelBuilder.Entity("Backend.Models.TagImply", b =>
                {
                    b.Property<long>("PrimaryTagId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ToApplyTagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PrimaryTagId", "ToApplyTagId");

                    b.HasIndex("ToApplyTagId");

                    b.ToTable("TagImplies");
                });

            modelBuilder.Entity("Backend.Models.TagModifier", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TagModifiers");
                });

            modelBuilder.Entity("Backend.Models.TagModifierAlias", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("ModifierId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.HasIndex("ModifierId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TagModifierAliases");
                });

            modelBuilder.Entity("Backend.Models.TagSuperAlias", b =>
                {
                    b.Property<string>("Alias")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Expanded")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Alias");

                    b.HasIndex("Alias")
                        .IsUnique();

                    b.ToTable("TagSuperAliases");
                });

            modelBuilder.Entity("Backend.Models.UploadSection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayIndex")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("KeepTarget")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastImported")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameLowercase")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Selected")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DisplayIndex")
                        .IsUnique();

                    b.HasIndex("NameLowercase")
                        .IsUnique();

                    b.HasIndex("Selected")
                        .IsUnique()
                        .HasFilter("[Selected] = 1");

                    b.ToTable("UploadSections");
                });

            modelBuilder.Entity("Backend.Models.UploadSectionItem", b =>
                {
                    b.Property<long>("UploadSectionId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MediaFileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.HasKey("UploadSectionId", "MediaFileId");

                    b.HasIndex("MediaFileId");

                    b.HasIndex("UploadSectionId", "Index")
                        .IsUnique();

                    b.ToTable("UploadSectionItems");
                });

            modelBuilder.Entity("CollectionMediaFolder", b =>
                {
                    b.Property<long>("ContainedCollectionsId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FoldersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ContainedCollectionsId", "FoldersId");

                    b.HasIndex("FoldersId");

                    b.ToTable("MediaFolderCollections", (string)null);
                });

            modelBuilder.Entity("DualView.Shared.Models.DualViewSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AIRunManagerAccessKey")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("AIRunManagerUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("AudioBufferingMs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GUIStartupCommand")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalMediaStorageLocation")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("MediaFolderMediaFolder", b =>
                {
                    b.Property<long>("ParentsId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SubFoldersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ParentsId", "SubFoldersId");

                    b.HasIndex("SubFoldersId");

                    b.ToTable("MediaFolderSubFolders", (string)null);
                });

            modelBuilder.Entity("TagBreakRuleTagModifier", b =>
                {
                    b.Property<long>("ModifiersId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TagBreakRuleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ModifiersId", "TagBreakRuleId");

                    b.HasIndex("TagBreakRuleId");

                    b.ToTable("TagBreakRuleModifiers", (string)null);
                });

            modelBuilder.Entity("AppliedTagCollection", b =>
                {
                    b.HasOne("Backend.Models.AppliedTag", null)
                        .WithMany()
                        .HasForeignKey("AppliedTagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Collection", null)
                        .WithMany()
                        .HasForeignKey("CollectionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppliedTagMediaFile", b =>
                {
                    b.HasOne("Backend.Models.AppliedTag", null)
                        .WithMany()
                        .HasForeignKey("AppliedTagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.MediaFile", null)
                        .WithMany()
                        .HasForeignKey("MediaFilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppliedTagTagModifier", b =>
                {
                    b.HasOne("Backend.Models.AppliedTag", null)
                        .WithMany()
                        .HasForeignKey("AppliedTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.TagModifier", null)
                        .WithMany()
                        .HasForeignKey("ModifiersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Models.AppliedTag", b =>
                {
                    b.HasOne("Backend.Models.AppliedTag", "CombinedWith")
                        .WithMany()
                        .HasForeignKey("CombinedWithId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend.Models.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CombinedWith");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Backend.Models.CollectionItem", b =>
                {
                    b.HasOne("Backend.Models.Collection", "Collection")
                        .WithMany("Items")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.MediaFile", "MediaFile")
                        .WithMany("InCollections")
                        .HasForeignKey("MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("MediaFile");
                });

            modelBuilder.Entity("Backend.Models.IgnoredDuplicate", b =>
                {
                    b.HasOne("Backend.Models.MediaFile", "MediaFile1")
                        .WithMany()
                        .HasForeignKey("MediaFileId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.MediaFile", "MediaFile2")
                        .WithMany()
                        .HasForeignKey("MediaFileId2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaFile1");

                    b.Navigation("MediaFile2");
                });

            modelBuilder.Entity("Backend.Models.MediaFile", b =>
                {
                    b.HasOne("Backend.Models.MediaFile", "ParentMedia")
                        .WithMany("Children")
                        .HasForeignKey("ParentMediaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ParentMedia");
                });

            modelBuilder.Entity("Backend.Models.MediaImportInfo", b =>
                {
                    b.HasOne("Backend.Models.DownloadGallery", "DownloadGallery")
                        .WithMany("AssociatedImports")
                        .HasForeignKey("DownloadGalleryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend.Models.MediaFile", "MediaFile")
                        .WithOne("ImportInfo")
                        .HasForeignKey("Backend.Models.MediaImportInfo", "MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DownloadGallery");

                    b.Navigation("MediaFile");
                });

            modelBuilder.Entity("Backend.Models.Tag", b =>
                {
                    b.HasOne("Backend.Models.MediaFile", "ExampleMedia")
                        .WithMany()
                        .HasForeignKey("ExampleMediaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ExampleMedia");
                });

            modelBuilder.Entity("Backend.Models.TagAlias", b =>
                {
                    b.HasOne("Backend.Models.Tag", "Tag")
                        .WithMany("Aliases")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Backend.Models.TagBreakRule", b =>
                {
                    b.HasOne("Backend.Models.Tag", "ActualTag")
                        .WithMany()
                        .HasForeignKey("ActualTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActualTag");
                });

            modelBuilder.Entity("Backend.Models.TagImply", b =>
                {
                    b.HasOne("Backend.Models.Tag", "PrimaryTag")
                        .WithMany("Implies")
                        .HasForeignKey("PrimaryTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Tag", "ToApplyTag")
                        .WithMany("ImpliedBy")
                        .HasForeignKey("ToApplyTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrimaryTag");

                    b.Navigation("ToApplyTag");
                });

            modelBuilder.Entity("Backend.Models.TagModifierAlias", b =>
                {
                    b.HasOne("Backend.Models.TagModifier", "Modifier")
                        .WithMany("Aliases")
                        .HasForeignKey("ModifierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modifier");
                });

            modelBuilder.Entity("Backend.Models.UploadSectionItem", b =>
                {
                    b.HasOne("Backend.Models.MediaFile", "MediaFile")
                        .WithMany("InUploadSections")
                        .HasForeignKey("MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.UploadSection", "UploadSection")
                        .WithMany("Items")
                        .HasForeignKey("UploadSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaFile");

                    b.Navigation("UploadSection");
                });

            modelBuilder.Entity("CollectionMediaFolder", b =>
                {
                    b.HasOne("Backend.Models.Collection", null)
                        .WithMany()
                        .HasForeignKey("ContainedCollectionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.MediaFolder", null)
                        .WithMany()
                        .HasForeignKey("FoldersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediaFolderMediaFolder", b =>
                {
                    b.HasOne("Backend.Models.MediaFolder", null)
                        .WithMany()
                        .HasForeignKey("ParentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.MediaFolder", null)
                        .WithMany()
                        .HasForeignKey("SubFoldersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TagBreakRuleTagModifier", b =>
                {
                    b.HasOne("Backend.Models.TagModifier", null)
                        .WithMany()
                        .HasForeignKey("ModifiersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.TagBreakRule", null)
                        .WithMany()
                        .HasForeignKey("TagBreakRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Models.Collection", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Backend.Models.DownloadGallery", b =>
                {
                    b.Navigation("AssociatedImports");
                });

            modelBuilder.Entity("Backend.Models.MediaFile", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("ImportInfo");

                    b.Navigation("InCollections");

                    b.Navigation("InUploadSections");
                });

            modelBuilder.Entity("Backend.Models.Tag", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("ImpliedBy");

                    b.Navigation("Implies");
                });

            modelBuilder.Entity("Backend.Models.TagModifier", b =>
                {
                    b.Navigation("Aliases");
                });

            modelBuilder.Entity("Backend.Models.UploadSection", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
